#include <iostream>
#include <limits>
#include <algorithm>
#include <ctime>
#include <cstdlib>
#include <iomanip>
#include <fstream>

using namespace std;

void manuallyGeneratedGame();

void autoGeneratedGame();

int main () {
    int i;
    cout << "press any key to proceed... ";
    cin >> i;
    int x;
    bool valid=true;
    bool again=true;
    do{
        cout << "\nWhat do you want to do?\n\n";
        do{
            cout << "Choose between\n(1).Manually generating the game\n(2).Auto generating the game\n";
            cin.clear();
            cin.ignore(numeric_limits<streamsize>::max(),'\n');
            cin >> x;
            if (x==1){
                valid=false;
                manuallyGeneratedGame();
            }
            if (x==2){
                valid = false;
                autoGeneratedGame();
            }
        }while(valid);
        cout << "Wanna go again?\n(1).Yes\n(0).No\n";
        cin >> again;
    }while(again);
}

void manuallyGeneratedGame() {
    int ** gameField = new int * [ 4 ];
    for (int i=0; i < 4; i++)
        gameField[i] = new int [4];

    int count=0;
    int number;
    for (int i = 0; i < 4; i++){
        for(int j=0; j < 4; j++){
            bool exists = true;
            if (count!=15){
                do {
                    do {
                        cout << "Please choose a unique number from 1-20 for the " << i << "," << j << " position\n";
                        cin.clear();
                        cin.ignore(numeric_limits<streamsize>::max(),'\n');
                        cin >> number;

                        for (int ii = 0; ii < 4; ii++){
                            for(int jj=0; jj < 4; jj++){
                                int* currentElement = &(gameField[ii][jj]);
                                if (number >20 || number < 1){
                                    cout << "Value must be between 1-20\n";
                                    exists =true;
                                    break;
                                }
                                if (*currentElement == number){
                                    cout << "Value exists " << *currentElement <<  endl;
                                    exists = true;
                                    break;
                                }else{
                                    exists = false;
                                }
                            }
                            if (exists)
                                break;
                        }
                        gameField[i][j] = number;
                    }while(exists);
                }while(cin.fail());
                count++;
            }else{
                gameField[i][j] =0;
            }
        }
    }
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 4; j++) {
            cout << "| " << setw(2) << gameField[i][j] << " |";
        }
        cout << "\n";
    }
}

void autoGeneratedGame() {
    int puzzles;
    bool exportFile;
    ofstream gameFile;

    do{
        cout << "How many puzzles do you want?\n";
        cin.clear();
        cin.ignore(numeric_limits<streamsize>::max(),'\n');
        cin >> puzzles;
    }while(cin.fail());

    cout << "Do you want to export your results to a .txt file?\n";

    do{
        cout << "Enter (0) for no and (1) for yes\n";
        cin.clear();
        cin.ignore(numeric_limits<streamsize>::max(),'\n');
        cin >> exportFile;
    }while(cin.fail());
    if(exportFile){
        gameFile.open ("15-file.txt");
    }
    cout << puzzles << ".\n";
    gameFile << puzzles <<"\n";

    srand(time(nullptr));

    int ** gameField = new int * [ 4 ];
    for (int i=0; i < 4; i++)
        gameField[i] = new int [4];

    for (int p = 0; p < puzzles; p++){
        cout << p+1 <<".\n";

        int count=0;
        for (int i = 0; i < 4; i++){
            for(int j=0; j < 4; j++){
                bool exists = true;
                if (count!=15){
                    do {
                        do {
                            int randomval = rand() % 20;

                            cin.clear();

                            for (int ii = 0; ii < 4; ii++){
                                for(int jj=0; jj < 4; jj++){
                                    int* currentElement = &(gameField[ii][jj]);
                                    if (randomval >20 || randomval < 1){
                                        exists =true;
                                        break;
                                    }
                                    if (*currentElement == randomval){
                                        exists = true;
                                        break;
                                    }else{
                                        exists = false;
                                    }
                                }
                                if (exists)
                                    break;
                            }
                            gameField[i][j] = randomval;
                        }while(exists);
                    }while(cin.fail());
                    count++;
                }else{
                    gameField[i][j] =0;
                }
            }
        }

        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                cout << "| " << setw(2) << gameField[i][j] << " |";
                gameFile << setw(2) << gameField[i][j] << " ";
            }
            cout << "\n";
            gameFile << "\n";
        }
        gameFile << "\n";
    }
    if (gameFile.is_open()){
        gameFile.close();
    }
}